#!/bin/bash
# Script that performs the needed BEDPOSTX processing in the input folder data.

usage(){
  echo "  bedpostx_processing"
  echo "    Script that performs the needed BEDPOSTX processing in the input folder data."
  echo ""
  echo "  $(basename $0) <DWI data> <Bval file> <Bvec file> [BET options] [BEDPOSTX options]"
  echo "      <> = The output folder where are the essentials files to create the connectivity matrix"
  echo "      <> = The cortical labels image that you want to build the connectivity matrix. It could be used any cortical label set, such as Harvard Oxford, MNI and others."
}

if [[ $# -lt 2 ]]; then
  usage
  exit
fi

DATA=$1
BVALS=$2
BVECS=$3
BETOP=$4
BEDPOSTXOPT=$5

#if [[ "$BETOP" == "" ]]; then
#  BETOP="-f 0.3"
#fi

#if [[ "$BEDPOSTXOPT" == "" ]]; then
#  BEDPOSTXOPT=""
#fi

echo "BEDPOSTX file formating on folder $(dirname $DATA)"
#Renaming the input files to be organized in the BEDPOSTX pattern
mkdir $(dirname $DATA)/BrainConnMatrix.data
cp $DATA $(dirname $DATA)/BrainConnMatrix.data/data.nii.gz
cp $BVALS $(dirname $DATA)/BrainConnMatrix.data/bvals
cp $BVECS $(dirname $DATA)/BrainConnMatrix.data/bvecs

#Creating the brain mask
if [[ ! -e $(dirname $DATA)/BrainConnMatrix.data/nodif_brain_mask.nii.gz ]]; then
  bet $DATA $(dirname $DATA)/BrainConnMatrix.data/nodif_brain -v -m $BETOP
  echo "***"
  printf "TIP: Check if the brain mask was correctly made (file: nodif_brain_mask.nii.gz). \nIf this was not the case, stop the process and change the BET options.\n"
  echo "***"
else
  echo "Brain mask detected as file: $(dirname $DATA)/nodif_brain_mask.nii.gz"
  echo "This mask will be used for further image processing."
fi

echo "BEDPOSTX processing...this may take several hours"
# Running BEDPOSTX
echo "Calling BEDPOSTX with the following line: bedpostx $(dirname $DATA)/BrainConnMatrix.data $BEDPOSTXOPT"
bedpostx $(dirname $DATA)/BrainConnMatrix.data $BEDPOSTXOPT

# Registration between native and MNI space
flirt -in $(dirname $DATA)/BrainConnMatrix.data/nodif_brain -ref $FSLDIR/data/standard/MNI152_T1_2mm_brain -omat $(dirname $DATA)/BrainConnMatrix.data.bedpostX/xfms/diff2standard.mat -searchrx -90 90 -searchry -90 90 -searchrz -90 90 -dof 12
convert_xfm -omat $(dirname $DATA)/BrainConnMatrix.data.bedpostX/xfms/standard2diff.mat -inverse $(dirname $DATA)/BrainConnMatrix.data.bedpostX/xfms/diff2standard.mat
