#!/bin/bash
# Scripts to reformat the XML file tags into a simple Nx1 matrix, which N is the number of tags.

usage(){
  echo "  XML reformat"
  echo "    Scripts to reformat the XML file tags into a simple Nx1 matrix, which N is the number of tags"
  echo ""
  echo "  $(basename $0) <XML file>"
  echo "      <XML file> = The FSL atlas XML file which name each cortical label. Use it if your cortical label image file come from FSL atlas folder"
}

XMLLABELS=$1
NUM_LABELS=$2
OUTPUT_FOLDER=$3

`cat $MASK_FOLDER/$file | grep DICE | awk '{print $3}'`

while read -r line
do
  if [[ ! `echo $line | grep index=` == ""  ]]; then
    `echo $line | grep index=\" | awk '{print $3}'` >> ${OUTPUT_FOLDER}/XML_tags.txt
  fi
done < "$XMLLABELS"
